python run_prespiked.py --name completeCases --patients 100
python run_prespiked.py --name completeCases --patients 200
python run_prespiked.py --name completeCases --patients 400
python run_prespiked.py --name completeCases --patients 800
python run_prespiked.py --name completeCases --patients 1600
python run_prespiked.py --name completeCases --patients 3200
python run_prespiked.py --name completeCases --patients 6400
python run_prespiked.py --name completeCases --patients 10000
python run_prespiked.py --name completeCases --patients 20000
python run_prespiked.py --name completeCasesBoxCox --patients 100
python run_prespiked.py --name completeCasesBoxCox --patients 200
python run_prespiked.py --name completeCasesBoxCox --patients 400
python run_prespiked.py --name completeCasesBoxCox --patients 800
python run_prespiked.py --name completeCasesBoxCox --patients 1600
python run_prespiked.py --name completeCasesBoxCox --patients 3200
python run_prespiked.py --name completeCasesBoxCox --patients 6400
python run_prespiked.py --name completeCasesBoxCox --patients 10000
python run_prespiked.py --name completeCasesBoxCox --patients 20000
python run_prespiked.py --name completeCasesBoxCox --patients 100
python run_prespiked.py --name completeCasesBoxCox --patients 200
python run_prespiked.py --name completeCasesBoxCox --patients 400
python run_prespiked.py --name completeCasesBoxCox --patients 800
python run_prespiked.py --name completeCasesBoxCox --patients 1600
python run_prespiked.py --name completeCasesBoxCox --patients 3200
python run_prespiked.py --name completeCasesBoxCox --patients 6400
python run_prespiked.py --name completeCasesBoxCox --patients 10000
python run_prespiked.py --name completeCasesBoxCox --patients 20000